//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthGovence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventWiseResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventWiseResult()
        {
            this.FirstPrizeTbls = new HashSet<FirstPrizeTbl>();
            this.SecondPrizeTbls = new HashSet<SecondPrizeTbl>();
            this.ThirdPrizeTbls = new HashSet<ThirdPrizeTbl>();
        }
    
        public long EvntID { get; set; }
        public string EventName { get; set; }
        public string FStudChestNumber { get; set; }
        public string FStudName { get; set; }
        public string FStudCollege { get; set; }
        public string SStudChestNumber { get; set; }
        public string SStudName { get; set; }
        public string SStudCollege { get; set; }
        public string TStudChestNumber { get; set; }
        public string TStudName { get; set; }
        public string TStudCollege { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<long> EnteredBy { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
        public virtual Volunteer Volunteer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirstPrizeTbl> FirstPrizeTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecondPrizeTbl> SecondPrizeTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThirdPrizeTbl> ThirdPrizeTbls { get; set; }
    }
}
