//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthGovence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMemParticiapation
    {
        public long GrpMemPartID { get; set; }
        public Nullable<long> GrpPartID { get; set; }
        public Nullable<long> TeamMemID { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual GroupHeadParticipation GroupHeadParticipation { get; set; }
        public virtual Student Student { get; set; }
    }
}
