//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthGovence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndivijualResult
    {
        public long IndvID { get; set; }
        public string StudName { get; set; }
        public string StudPoint { get; set; }
        public string StudCollege { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> EnteredBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
        public virtual Volunteer Volunteer1 { get; set; }
    }
}
