//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthGovence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long NewsID { get; set; }
        public string NewsTitle { get; set; }
        public string NewsInfo { get; set; }
        public string NewsLink { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
    }
}
