//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthGovence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantMaleResult
    {
        public long PartMaleResultID { get; set; }
        public string StudName { get; set; }
        public string CollegeName { get; set; }
        public Nullable<long> StudPoint { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
