//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthGovence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrgShedule
    {
        public long SheduleID { get; set; }
        public string EventName { get; set; }
        public string EventCode { get; set; }
        public Nullable<System.DateTime> SheduleDate { get; set; }
        public string StartingTime { get; set; }
        public string EndingTime { get; set; }
        public string Stage { get; set; }
        public string CollegeName { get; set; }
        public string CoOrdinatorName { get; set; }
        public string CoOrdinatorNumber { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<long> EnteredBy { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
        public virtual Volunteer Volunteer1 { get; set; }
    }
}
