//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthGovence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleParticipation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SingleParticipation()
        {
            this.StudentChestNoes = new HashSet<StudentChestNo>();
        }
    
        public long StudPartID { get; set; }
        public Nullable<long> StudID { get; set; }
        public Nullable<long> SinEvtID { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual SingleEvent SingleEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentChestNo> StudentChestNoes { get; set; }
        public virtual Student Student { get; set; }
    }
}
