//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthGovence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.GroupHeadParticipations = new HashSet<GroupHeadParticipation>();
            this.GroupMemParticiapations = new HashSet<GroupMemParticiapation>();
            this.SingleParticipations = new HashSet<SingleParticipation>();
        }
    
        public long StudID { get; set; }
        public Nullable<long> CredID { get; set; }
        public string RegID { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string Sex { get; set; }
        public string ClgAdmistnNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ProPic { get; set; }
        public Nullable<long> ColID { get; set; }
        public Nullable<long> DeptID { get; set; }
        public Nullable<long> CouID { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsPhoneVerify { get; set; }
        public string PhoneVerificationCode { get; set; }
        public Nullable<bool> IsCollegeApproved { get; set; }
        public Nullable<bool> IsEligibilityApproved { get; set; }
        public Nullable<bool> IsChestNoProvided { get; set; }
        public Nullable<long> CollegeApprovedBy { get; set; }
        public Nullable<long> EligibilityApprovedBy { get; set; }
        public Nullable<long> ChestNoProvidedBy { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual College College { get; set; }
        public virtual Course Course { get; set; }
        public virtual Credential Credential { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupHeadParticipation> GroupHeadParticipations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMemParticiapation> GroupMemParticiapations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SingleParticipation> SingleParticipations { get; set; }
    }
}
