//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthGovence.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<College> Colleges { get; set; }
        public virtual DbSet<CollegeResult> CollegeResults { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EventWiseResult> EventWiseResults { get; set; }
        public virtual DbSet<FirstPrizeTbl> FirstPrizeTbls { get; set; }
        public virtual DbSet<GeneralSetting> GeneralSettings { get; set; }
        public virtual DbSet<GroupHeadParticipation> GroupHeadParticipations { get; set; }
        public virtual DbSet<GroupMemParticiapation> GroupMemParticiapations { get; set; }
        public virtual DbSet<GrpEvent> GrpEvents { get; set; }
        public virtual DbSet<ImageGallery> ImageGalleries { get; set; }
        public virtual DbSet<IndivijualResult> IndivijualResults { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<ParticipantFeMaleResult> ParticipantFeMaleResults { get; set; }
        public virtual DbSet<ParticipantMaleResult> ParticipantMaleResults { get; set; }
        public virtual DbSet<PrgShedule> PrgShedules { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SecondPrizeTbl> SecondPrizeTbls { get; set; }
        public virtual DbSet<SingleEvent> SingleEvents { get; set; }
        public virtual DbSet<SingleParticipation> SingleParticipations { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentChestNo> StudentChestNoes { get; set; }
        public virtual DbSet<SuperAdmin> SuperAdmins { get; set; }
        public virtual DbSet<ThirdPrizeTbl> ThirdPrizeTbls { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
    }
}
